// GENERATED BY ReactGenius -- re-injecting overwrites this file.
//
// The board. Two sidebar panels:
//
//   Pages       -- the site's real routes, each loading the actual app URL, so you
//                  see the whole thing: router, layout chrome, navbar, footer.
//   Components  -- single components from the watched directory, each mounted alone
//                  in a bare host page.
//
// Both render as live iframes on the right and can be mixed freely.

import React, { useEffect, useMemo, useRef, useState } from 'react'
import ReactDOM from 'react-dom/client'
import { modules, moduleName, GLOB_LABEL } from './modules'
import { overrides, DEFAULT_WIDTH, DEFAULT_HEIGHT } from './config'
import { routes } from './routes'

const PRESETS = {
    desktop: { w: DEFAULT_WIDTH, h: DEFAULT_HEIGHT, label: 'Desktop' },
    tablet: { w: 768, h: 1024, label: 'Tablet' },
    mobile: { w: 375, h: 812, label: 'Mobile' },
} as const
type PresetKey = keyof typeof PRESETS

const BASE = import.meta.env.BASE_URL

/** A single component, mounted alone in the bare frame host. */
const componentURL = (mod: string) =>
    `${BASE}devframe.html?mod=${encodeURIComponent(mod)}`

/** A real page of the site, at its actual route. */
const pageURL = (path: string) => BASE + path.replace(/^\//, '')

interface Item {
    id: string
    kind: 'page' | 'component'
    label: string
    url: string
    /** Config-driven size, components only. */
    width?: number
    height?: number
    note?: string
}

const pageItems: Item[] = routes.map((r) => ({
    id: `page:${r.path}`,
    kind: 'page',
    label: r.label,
    url: pageURL(r.path),
    note: r.path,
}))

const componentItems: Item[] = Object.keys(modules)
    .filter((m) => !overrides[m]?.skip)
    .sort()
    .map((m) => ({
        id: m,
        kind: 'component',
        label: moduleName(m),
        url: componentURL(m),
        width: overrides[m]?.width,
        height: overrides[m]?.height,
        note: overrides[m]?.note,
    }))

// Persist which frames are hidden, not which are shown, so something added to the
// project later appears by default instead of silently staying hidden.
const STORE_KEY = 'reactgenius:excluded'

function loadExcluded(): Set<string> {
    try {
        const raw = localStorage.getItem(STORE_KEY)
        return new Set(raw ? (JSON.parse(raw) as string[]) : [])
    } catch {
        return new Set()
    }
}

/** Mount an iframe only once its card is near the viewport -- live iframes are expensive. */
function useNearViewport<T extends HTMLElement>(ref: React.RefObject<T>, margin = '600px') {
    const [near, setNear] = useState(false)
    useEffect(() => {
        const el = ref.current
        if (!el || near) return
        const io = new IntersectionObserver(
            (entries) => entries.forEach((e) => e.isIntersecting && setNear(true)),
            { rootMargin: margin }
        )
        io.observe(el)
        return () => io.disconnect()
    }, [ref, near, margin])
    return near
}

const selectStyle: React.CSSProperties = {
    background: '#262a31', color: '#dfe4ec', border: '1px solid #363b44',
    borderRadius: 5, font: '11px system-ui', padding: '2px 4px',
}
const btnStyle: React.CSSProperties = {
    background: '#262a31', color: '#dfe4ec', border: '1px solid #363b44',
    borderRadius: 6, padding: '4px 10px', font: '12px system-ui', cursor: 'pointer',
}
const miniBtn: React.CSSProperties = { ...btnStyle, padding: '2px 8px', font: '11px system-ui' }

function Card({ item, preset, zoom, flashed, reloadKey }: {
    item: Item; preset: PresetKey; zoom: number; flashed: boolean; reloadKey: number
}) {
    const ref = useRef<HTMLDivElement>(null)
    const near = useNearViewport(ref)
    const [own, setOwn] = useState<PresetKey | null>(null)

    // Per-frame override wins, then the config's size, then the board preset.
    const active = own ?? preset
    const width = own ? PRESETS[active].w : item.width ?? PRESETS[active].w
    const height = own ? PRESETS[active].h : item.height ?? PRESETS[active].h
    const isPage = item.kind === 'page'

    return (
        <div ref={ref} id={`card-${item.id}`} style={{
            border: `1px solid ${flashed ? '#4c8dff' : isPage ? '#33405c' : '#2a2d34'}`,
            boxShadow: flashed ? '0 0 0 3px rgba(76,141,255,.25)' : 'none',
            transition: 'border-color .25s, box-shadow .25s',
            borderRadius: 10, background: '#15171b', overflow: 'hidden',
            width: width * zoom + 2, scrollMarginTop: 70,
        }}>
            <div style={{
                display: 'flex', alignItems: 'center', gap: 8, padding: '7px 10px',
                background: isPage ? '#1b2233' : '#1d2026',
                borderBottom: '1px solid #2a2d34',
                font: '12px system-ui', color: '#c9ced8',
            }}>
                <span style={{
                    font: '9px system-ui', letterSpacing: .5, padding: '1px 5px',
                    borderRadius: 4, textTransform: 'uppercase',
                    background: isPage ? '#2c3f66' : '#31363f',
                    color: isPage ? '#b9d2ff' : '#aeb6c2',
                }}>{isPage ? 'Page' : 'Cmp'}</span>

                <strong style={{ color: '#fff' }}>{item.label}</strong>
                {item.note && <span style={{ opacity: 0.5 }}>{item.note}</span>}
                <span style={{ marginLeft: 'auto', opacity: 0.5 }}>{width}×{height}</span>

                <select value={active} onChange={(e) => setOwn(e.target.value as PresetKey)}
                        style={selectStyle} title="Viewport for this frame">
                    {Object.entries(PRESETS).map(([k, v]) => (
                        <option key={k} value={k}>{v.label}</option>
                    ))}
                </select>
                <a href={item.url} target="_blank" rel="noreferrer"
                   style={{ color: '#8fb4ff', textDecoration: 'none', padding: '0 4px', fontSize: 13 }}
                   title="Open in a tab">↗</a>
            </div>

            <div style={{
                width: width * zoom, height: height * zoom,
                background: '#0b0c0f', overflow: 'hidden',
            }}>
                {near ? (
                    // CSS `zoom`, not `transform: scale()`: zoom scales at layout level,
                    // so the frame's own viewport stays `width` wide and its media
                    // queries fire as they would at that real size.
                    //
                    // Note: some offscreen/headless renderers fail to composite a scaled
                    // iframe and show a blank box even though the frame has loaded and
                    // rendered. Real Safari and Chrome paint it correctly.
                    <iframe key={`${item.id}:${reloadKey}`} src={item.url} title={item.label}
                        style={{ width, height, border: 0, display: 'block', zoom }} />
                ) : (
                    <div style={{
                        width: '100%', height: '100%', display: 'grid', placeItems: 'center',
                        font: '12px system-ui', color: '#555b66',
                    }}>scroll to load</div>
                )}
            </div>
        </div>
    )
}

function SidebarSection({ title, subtitle, items, excluded, query, flash, errored, onToggle, onSolo, onBulk }: {
    title: string
    subtitle?: string
    items: Item[]
    excluded: Set<string>
    query: string
    flash: Record<string, number>
    errored: Set<string>
    onToggle: (id: string) => void
    onSolo: (id: string) => void
    onBulk: (ids: string[], hide: boolean) => void
}) {
    const listed = items.filter((i) => i.label.toLowerCase().includes(query.toLowerCase()))
    const onCount = items.filter((i) => !excluded.has(i.id)).length

    return (
        <div style={{ borderBottom: '1px solid #23262d' }}>
            <div style={{
                display: 'flex', alignItems: 'baseline', gap: 6,
                padding: '10px 12px 6px',
            }}>
                <span style={{ font: '600 12px system-ui' }}>{title}</span>
                {subtitle && (
                    <code style={{ font: '10px ui-monospace, Menlo, monospace', opacity: 0.45 }}>
                        {subtitle}
                    </code>
                )}
                <span style={{ marginLeft: 'auto', font: '11px system-ui', opacity: 0.45 }}>
                    {onCount}/{items.length}
                </span>
            </div>

            <div style={{ display: 'flex', gap: 6, padding: '0 12px 8px' }}>
                <button style={miniBtn} onClick={() => onBulk(items.map((i) => i.id), false)}>All</button>
                <button style={miniBtn} onClick={() => onBulk(items.map((i) => i.id), true)}>None</button>
            </div>

            {listed.length === 0 && (
                <p style={{ padding: '0 12px 10px', font: '11px system-ui', opacity: 0.45 }}>
                    nothing matches
                </p>
            )}

            {listed.map((item) => {
                const on = !excluded.has(item.id)
                return (
                    <div key={item.id} style={{
                        display: 'flex', alignItems: 'center', gap: 8, padding: '5px 12px',
                        background: flash[item.id] ? 'rgba(76,141,255,.14)' : 'transparent',
                        transition: 'background .3s',
                    }}>
                        <input type="checkbox" checked={on} onChange={() => onToggle(item.id)}
                               title={on ? 'Hide from board' : 'Show on board'} />
                        <button onClick={() => onSolo(item.id)} title="Show only this one"
                            style={{
                                flex: 1, textAlign: 'left', background: 'none', border: 0,
                                cursor: 'pointer', padding: 0,
                                font: `${on ? 500 : 400} 12px system-ui`,
                                color: on ? '#e6eaf2' : '#6b7280',
                            }}>
                            {item.label}
                        </button>
                        {errored.has(item.id) && (
                            <span title="Error reported by this frame"
                                  style={{ color: '#ff8f8f', fontSize: 11 }}>!</span>
                        )}
                    </div>
                )
            })}
        </div>
    )
}

function Canvas() {
    const all = useMemo(() => [...pageItems, ...componentItems], [])

    const [excluded, setExcluded] = useState<Set<string>>(loadExcluded)
    const [query, setQuery] = useState('')
    const [preset, setPreset] = useState<PresetKey>('desktop')
    const [zoom, setZoom] = useState(0.5)
    const [reloadKey, setReloadKey] = useState(0)
    const [flash, setFlash] = useState<Record<string, number>>({})
    const [errored, setErrored] = useState<Set<string>>(new Set())
    const [lastEvent, setLastEvent] = useState('watching…')

    useEffect(() => {
        try {
            localStorage.setItem(STORE_KEY, JSON.stringify([...excluded]))
        } catch { /* private mode, non-fatal */ }
    }, [excluded])

    const shown = all.filter(
        (i) => !excluded.has(i.id) && i.label.toLowerCase().includes(query.toLowerCase())
    )

    // Component frames report their own hot-updates up to us. Page frames are the
    // real app, so they hot-update themselves without telling us.
    useEffect(() => {
        function onMsg(e: MessageEvent) {
            const d = e.data
            if (d?.type === 'canvas:updated') {
                setFlash((f) => ({ ...f, [d.mod]: Date.now() }))
                setErrored((s) => {
                    if (!s.has(d.mod)) return s
                    const next = new Set(s); next.delete(d.mod); return next
                })
                setLastEvent(`${moduleName(d.mod)} updated ${new Date().toLocaleTimeString()}`)
                setTimeout(() => setFlash((f) => ({ ...f, [d.mod]: 0 })), 1200)
            }
            if (d?.type === 'canvas:error') {
                setErrored((s) => new Set(s).add(d.mod))
                setLastEvent(`error in ${moduleName(d.mod)} — see frame`)
            }
        }
        addEventListener('message', onMsg)
        return () => removeEventListener('message', onMsg)
    }, [])

    const toggle = (id: string) =>
        setExcluded((s) => {
            const next = new Set(s)
            next.has(id) ? next.delete(id) : next.add(id)
            return next
        })

    const bulk = (ids: string[], hide: boolean) =>
        setExcluded((s) => {
            const next = new Set(s)
            ids.forEach((id) => (hide ? next.add(id) : next.delete(id)))
            return next
        })

    /** Show only this one, and scroll to it. */
    const solo = (id: string) => {
        setExcluded(new Set(all.map((i) => i.id).filter((x) => x !== id)))
        requestAnimationFrame(() =>
            document.getElementById(`card-${id}`)?.scrollIntoView({ behavior: 'smooth' })
        )
    }

    return (
        <div style={{
            display: 'flex', alignItems: 'flex-start',
            minHeight: '100vh', background: '#0e1013', color: '#e6eaf2',
        }}>
            <aside style={{
                width: 250, flex: '0 0 250px', position: 'sticky', top: 0,
                height: '100vh', overflowY: 'auto',
                borderRight: '1px solid #23262d', background: '#121418',
            }}>
                <div style={{ padding: '12px 12px 8px' }}>
                    <input placeholder="Filter…" value={query} onChange={(e) => setQuery(e.target.value)}
                        style={{
                            width: '100%', boxSizing: 'border-box',
                            background: '#1b1e24', border: '1px solid #2f343d', borderRadius: 6,
                            color: '#e6eaf2', padding: '5px 8px', font: '12px system-ui',
                        }} />
                </div>

                <SidebarSection
                    title="Pages" subtitle="site routes" items={pageItems}
                    excluded={excluded} query={query} flash={flash} errored={errored}
                    onToggle={toggle} onSolo={solo} onBulk={bulk}
                />
                <SidebarSection
                    title="Components" subtitle={GLOB_LABEL} items={componentItems}
                    excluded={excluded} query={query} flash={flash} errored={errored}
                    onToggle={toggle} onSolo={solo} onBulk={bulk}
                />

                <div style={{ display: 'flex', gap: 6, padding: 12 }}>
                    <button style={miniBtn} onClick={() => setExcluded(new Set())}>Show all</button>
                    <button style={miniBtn}
                            onClick={() => setExcluded(new Set(all.map((i) => i.id)))}>Hide all</button>
                </div>
            </aside>

            <main style={{ flex: 1, minWidth: 0 }}>
                <header style={{
                    position: 'sticky', top: 0, zIndex: 10, display: 'flex', alignItems: 'center',
                    gap: 14, padding: '10px 14px', background: 'rgba(14,16,19,.92)',
                    backdropFilter: 'blur(8px)', borderBottom: '1px solid #23262d',
                    font: '13px system-ui', flexWrap: 'wrap',
                }}>
                    <strong style={{ fontSize: 14 }}>Component Canvas</strong>

                    <label style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                        Viewport
                        <select value={preset} onChange={(e) => setPreset(e.target.value as PresetKey)}
                                style={selectStyle}>
                            {Object.entries(PRESETS).map(([k, v]) => (
                                <option key={k} value={k}>{v.label}</option>
                            ))}
                        </select>
                    </label>

                    <label style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                        Zoom {Math.round(zoom * 100)}%
                        <input type="range" min={0.2} max={1} step={0.05} value={zoom}
                               onChange={(e) => setZoom(Number(e.target.value))} />
                    </label>

                    <button onClick={() => setReloadKey((k) => k + 1)} style={btnStyle}>Reload all</button>

                    <span style={{ marginLeft: 'auto', opacity: 0.6, fontSize: 12 }}>
                        {shown.length} shown · {lastEvent}
                    </span>
                </header>

                {shown.length === 0 ? (
                    <p style={{ padding: 24, opacity: 0.6, font: '13px system-ui' }}>
                        Nothing selected. Tick something in the sidebar, or press <b>Show all</b>.
                    </p>
                ) : (
                    <div style={{
                        display: 'flex', flexWrap: 'wrap', gap: 16,
                        alignItems: 'flex-start', padding: 16,
                    }}>
                        {shown.map((item) => (
                            <Card key={item.id} item={item} preset={preset} zoom={zoom}
                                  reloadKey={reloadKey} flashed={Boolean(flash[item.id])} />
                        ))}
                    </div>
                )}
            </main>
        </div>
    )
}

ReactDOM.createRoot(document.getElementById('canvas-root')!).render(<Canvas />)
