// GENERATED BY ReactGenius -- re-injecting overwrites this file.
//
// The site's real pages, found by scanning the project for router paths.
// A page frame loads the actual app URL, so you get the full thing: router,
// layout chrome, navbar, footer -- exactly what a visitor sees.

export interface PageRoute {
    path: string
    label: string
}

export const routes: PageRoute[] = [
    { path: '/', label: 'Home' },
    { path: '/about', label: 'About' },
    { path: '/dataset', label: 'Dataset' },
    { path: '/faq', label: 'FAQ' },
    { path: '/feedback', label: 'Feedback' },
    { path: '/search', label: 'Search' },
]
